# -*- coding: utf-8 -*-
"""Pole_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7tQ1l4IPPNMevFkq47PkhAuS7pbkPCL

#Les imports
"""

!pip install pyarrow

import pandas as pd
import numpy as np

colors = pd.read_parquet("auto_color.parquet")
choix = pd.read_parquet("choix_vehicule.parquet")

"""#Nettoyage"""

colors.isna().sum()
choix.isna().sum()

colors['Effet'].unique()

Ncolors = colors.drop(columns=['Catégorie', 'Code de couleur', 'Couleur apprêt', 'Variante','Système'])
Nchoix = choix.drop(columns=['usage', 'presentation_video', 'reprise_energie', 'reprise_annee', 'reprise_modele', 'kms_min','kms_max', 'kms_reprise', 'modele_concurrence', 'marque_concurrence'])

Ncolors['Nom'].value_counts()

Ncolors['Nom'].value_counts(normalize=True) * 100

import plotly.express as px

# The columns after reset_index() are 'Nom' and 'count'
fig = px.bar(Ncolors['Nom'].value_counts().reset_index(),
             x='Nom', y='count',
             title="Distribution des couleurs")
fig.show()

Ncolors.groupby(['Marque', 'Nom']).size().reset_index(name='count')

pd.crosstab(Ncolors['Marque'], Ncolors['Nom'], normalize = 'index')

Ncolors.groupby(['Année debut', 'Nom']).size().reset_index(name='count')

pivot = Ncolors.groupby(['Année debut', 'Couleur dominante']).size().unstack()

pivot.plot(figsize=(20, 10))
pivot.plot()